// ---- v5: 학파마다 위계별 선택지를 늘린 마법 (룬의 계승자 설정집의 학파 목록에서) ----
// 화염
def('mage',1,'ember','불씨','Ember','fire','cone',3,.6,{mult:.9,range:150,ang:1.1,burn:1},'손끝의 불씨를 앞쪽으로 흩뿌려 불붙입니다. 맞은 적은 3초간 탑니다.');
def('mage',1,'warmth','온기','Warmth','fire','passive',0,0,{pv:{regen:[1,.4],dmg:[.02,.003]}},'몸속에 늘 온기를 품습니다. 패시브: 마나 회복과 마법 피해가 늘 조금 오릅니다.');
def('mage',2,'dancingflames','불빛 춤','Dancing Flames','fire','orbit',10,8,{mult:.7,orbs:3,orad:62,dur:6,burn:1},'불꽃 셋을 띄워 내 둘레를 돌게 합니다. 닿는 적을 태웁니다.');
def('mage',2,'smokecall','연기 부르기','Smoke Call','fire','field',9,7,{mult:.25,rad:110,dur:5,slow:1},'짙은 연기로 한 곳을 덮어 안의 적을 느리게 하고 숨을 막습니다.');
def('mage',2,'flameshaping','불꽃 다루기','Flame Shaping','fire','nova',8,3,{mult:.9,rad:150,burn:1},'둘레의 불기운을 한꺼번에 부풀려 터뜨립니다.');
def('mage',3,'flamelash','불꽃 채찍','Flame Lash','fire','cone',8,1.2,{mult:1.5,range:210,ang:.45,knock:50,burn:1},'불을 가늘고 길게 벼려 채찍처럼 휘두릅니다. 멀리 닿습니다.');
def('mage',3,'steamjet','증기 뿜기','Steam Jet','fire','beam',9,1.4,{mult:1.4,len:230,w:26,slow:1,burn:1},'물을 순식간에 끓여 뜨거운 김을 뿜습니다. 물 학파와의 첫 융합.');
def('mage',4,'flamemantle','불의 갑옷','Mantle of Flame','fire','armor',18,18,{mult:.9,dur:15,red:.15,burn:1},'몸에 불을 둘러 15초 동안 받는 피해를 줄이고, 나를 때린 적을 태웁니다.');
def('mage',4,'blazinggust','불붙은 바람','Blazing Gust','fire','cone',14,2.5,{mult:1.7,range:190,ang:1.3,knock:110,burn:1},'바람에 불을 실어 넓은 부채꼴로 흩뿌립니다.');
def('mage',5,'ringoffire','화염 원','Ring of Fire','fire','field',22,10,{mult:.55,rad:125,dur:6,self:1,burn:1},'나를 중심으로 불의 고리를 둘러 가까이 오는 것을 태웁니다.');
def('mage',5,'flamelance','불빛 창','Flame Lance','fire','bolt',12,1,{mult:2.3,spd:900,r:7,pierce:1,burn:1},'불을 가늘게 모아 멀리 있는 적까지 줄지어 꿰뚫습니다.');
def('mage',6,'firestorm','화염 폭풍','Firestorm','fire','field',30,9,{mult:.7,rad:150,dur:5,pull:1,burn:1},'불 섞인 회오리를 일으켜 적을 한가운데로 끌어당기며 태웁니다.');
def('mage',7,'callmagma','화산 불러내기','Call the Magma','fire','field',38,12,{mult:1.1,rad:170,dur:6,burn:1,stun:.2},'땅속 깊은 용암을 끌어올려 좁은 땅을 불바다로 만듭니다.');
def('mage',8,'heartoffire','불의 심장','Heart of Fire','fire','armor',45,75,{mult:1.4,burst:1,dur:12,red:.3,aura:130,dmg:.25,burn:1},'몸을 잠시 살아 있는 불로 바꿉니다. 피해 25% 증가, 둘레의 적을 계속 태웁니다.');
def('mage',9,'seaofflame','불바다','Sea of Flame','fire','field',70,35,{mult:1.5,rad:280,dur:7,burn:1},'한 고을을 끝없는 불길로 덮는 금기의 전쟁 마법.');
// 냉기 (물과 얼음)
def('mage',1,'splash','물 끼얹기','Splash','ice','bolt',3,.35,{mult:.9,spd:600,r:6,slow:1},'물을 끼얹어 적을 느리게 합니다.');
def('mage',1,'drawwater','물 끌어오기','Draw Water','ice','nova',6,3,{mult:.7,rad:140,knock:70},'땅속의 물을 한꺼번에 끌어올려 둘레의 적을 밀어냅니다.');
def('mage',1,'purifywater','물 맑히기','Purify Water','ice','passive',0,0,{pv:{regen:[2,1.5]}},'몸속 마나의 흐름을 늘 맑게 유지합니다. 언제나 켜져 있는 패시브: 초당 마나 회복이 스킬 레벨마다 크게 오릅니다.');
def('mage',2,'watershaping','물 다루기','Water Shaping','ice','orbit',10,8,{mult:.6,orbs:4,orad:58,dur:6,slow:1},'물줄기 넷을 띄워 둘레를 돌게 합니다. 닿는 적이 느려집니다.');
def('mage',2,'gatherdew','이슬 모으기','Gather Dew','life','heal',12,10,{pct:.12,mult:.8},'공기 속 물기를 모아 상처를 씻어 냅니다.');
def('mage',3,'waterwhip','물 채찍','Water Whip','ice','cone',8,1.1,{mult:1.4,range:200,ang:.5,knock:60,slow:1},'물을 날처럼 벼려 채찍으로 휘두릅니다.');
def('mage',3,'mire','진흙 늪','Mire','ice','field',12,8,{mult:.3,rad:130,dur:6,slow:1},'발밑 땅을 진흙으로 바꿔 적의 발을 묶습니다. 대지 학파와의 융합.');
def('mage',4,'iceshield','얼음 방패','Ice Shield','ice','shield',16,14,{mult:3.2,flat:20,dur:10},'얼음 벽으로 몸을 가려 10초 동안 피해를 흡수합니다.');
def('mage',4,'iceblade','얼음 칼','Ice Blade','ice','cone',12,1.6,{mult:2.2,range:120,ang:1.4,freeze:.8},'손에 얼음 칼날을 만들어 앞을 크게 벱니다. 맞은 적이 얼어붙습니다.');
def('mage',5,'shardvolley','얼음 조각 비','Ice Shard Volley','ice','bolt',16,1.4,{mult:1.1,spd:620,r:6,cnt:7,spread:.13,slow:1},'얼음 조각을 넓은 부채꼴로 흩뿌립니다.');
def('mage',5,'whirlpool','소용돌이','Whirlpool','ice','field',22,10,{mult:.5,rad:140,dur:5,pull:1,slow:1},'소용돌이를 일으켜 적을 한가운데로 끌어들입니다.');
def('mage',6,'callwave','파도 부르기','Call the Wave','ice','beam',26,5,{mult:2.6,len:380,w:60,knock:130,slow:1},'물을 일으켜 앞쪽의 적을 크게 밀어냅니다.');
def('mage',6,'frostarmor','얼음 갑옷','Frost Armor','ice','armor',22,20,{mult:.7,dur:20,red:.25,freeze:1.5},'얼음 갑옷을 둘러 피해를 줄이고, 나를 때린 적을 얼립니다.');
def('mage',7,'callrain','비 부르기','Call Rain','ice','rain',34,11,{mult:1.2,rad:170,dur:4,rate:8,srad:40,slow:1},'얼음 섞인 비를 불러 넓은 땅에 쏟습니다.');
def('mage',7,'icecitadel','얼음 성채','Ice Citadel','ice','shield',36,60,{mult:7,flat:80,dur:12,freeze:2,rad:160},'얼음 성채를 세워 큰 피해를 막고 둘레의 적을 얼립니다.');
def('mage',8,'endlesswinter','끝없는 겨울','Endless Winter','ice','field',48,30,{mult:.8,rad:220,dur:8,self:1,slow:1,freeze:.6},'내 둘레에 봄이 오지 않게 합니다. 8초 동안 적이 느려지고 얼어붙습니다.');
def('mage',8,'bodyofwater','물의 몸','Body of Water','ice','invuln',35,75,{dur:2.5,heal:.25},'몸을 잠시 물로 바꿔 칼과 화살이 지나가게 하고 상처를 씻습니다.');
def('mage',8,'turncurrent','해류 돌리기','Turn the Current','ice','cone',40,7,{mult:3.4,range:300,ang:1.5,knock:180,slow:1},'물의 흐름을 되돌려 앞쪽을 통째로 휩쓸어 밀어냅니다.');
def('mage',9,'tidalwave','대해일','Great Tidal Wave','ice','beam',65,16,{mult:6,len:620,w:120,knock:220,slow:1},'바다를 일으켜 앞쪽을 덮칩니다. 세레스의 기록에만 남아 있습니다.');
def('mage',9,'monsoon','우기','Monsoon','ice','rain',60,30,{mult:1.6,rad:230,dur:7,rate:9,srad:46,slow:1},'한 계절의 비를 한 번에 쏟습니다.');
// 폭풍 (대기)
def('mage',1,'breeze','산들바람','Breeze','wind','passive',0,0,{pv:{spd:[.05,.01],regen:[.5,.2]}},'늘 바람을 등에 받습니다. 패시브: 이동 속도와 마나 회복이 오릅니다.');
def('mage',1,'clearair','공기 맑히기','Clear Air','wind','nova',6,3,{mult:.6,rad:110,knock:90},'둘레의 공기를 한꺼번에 밀어내 적을 떼어 냅니다.');
def('mage',2,'windshaping','바람 다루기','Wind Shaping','wind','orbit',10,8,{mult:.65,orbs:3,orad:70,dur:6,knock:30},'바람 칼날 셋을 둘레에 돌게 합니다.');
def('mage',2,'windreading','바람 읽기','Wind Reading','wind','passive',0,0,{pv:{dmg:[.03,.004]}},'바람의 흐름을 늘 읽어 마법이 더 정확히 꽂힙니다. 패시브: 마법 피해가 조금 오릅니다(스킬 레벨마다 천천히).');
def('mage',3,'airwall','공기 방벽','Air Wall','wind','shield',14,14,{mult:2.8,flat:18,dur:10},'바람의 벽으로 날아오는 것을 흘립니다.');
def('mage',3,'dustdevil','먼지 바람','Dust Devil','wind','field',12,8,{mult:.45,rad:110,dur:5,slow:1},'흙먼지 회오리로 적의 눈을 가리고 느리게 합니다. 대지 학파와의 융합.');
def('mage',4,'shockinggrasp','번쩍이는 손','Shocking Grasp','storm','cone',10,1,{mult:2.3,range:160,ang:1.3,stun:.7},'손에 벼락을 담아 가까운 적을 마비시킵니다.');
def('mage',4,'doubledgust','겹쳐 부른 돌풍','Doubled Gust','wind','cone',14,3,{mult:1.6,range:240,ang:1.2,knock:170},'같은 말을 들숨과 날숨에 겹쳐 두 배의 돌풍을 부릅니다.');
def('mage',4,'windleap','도약','Wind Leap','wind','blink',14,5,{range:280,mult:1.2,w:60,knock:60},'바람을 타고 뛰어올라 내려앉으며 둘레를 밀어냅니다.');
def('mage',5,'whirlwind','회오리','Whirlwind','wind','field',24,9,{mult:.7,rad:120,dur:5,pull:1},'회오리로 적을 감싸 한곳에 끌어모읍니다.');
def('mage',5,'hail','우박','Hail','storm','rain',26,9,{mult:1,rad:140,dur:3,rate:7,srad:36,stun:.3,slow:1},'얼음 조각을 바람에 실어 퍼붓습니다. 물 학파와의 융합.');
def('mage',6,'sandstorm','모래 폭풍','Sandstorm','wind','field',32,12,{mult:.65,rad:200,dur:7,slow:1},'넓은 땅에 모래 폭풍을 일으켜 적을 느리게 깎아 냅니다.');
def('mage',6,'eyeofstorm','폭풍의 눈','Eye of the Storm','storm','nova',30,9,{mult:2,rad:190,knock:120,stun:.8},'폭풍 한가운데 고요를 만들며 둘레의 적을 벼락과 바람으로 날려 버립니다.');
def('mage',7,'vacuumblade','진공 칼날','Vacuum Blade','wind','bolt',22,1.2,{mult:3.4,spd:1000,r:9,pierce:1},'공기를 멈춰 만든 빈 칼날. 막을 수 없이 줄지어 꿰뚫습니다.');
def('mage',8,'lightningbody','번개의 몸','Body of Lightning','storm','blink',30,4,{range:420,mult:2.6,w:50,stun:.8},'몸을 벼락으로 바꿔 번쩍이는 사이 옮겨 가며, 지나간 길의 적을 마비시킵니다.');
def('mage',8,'thundervoice','천둥의 목소리','Thunderous Voice','storm','nova',44,10,{mult:3,rad:260,stun:1.4},'천둥 같은 목소리로 둘레의 모든 적을 벼락으로 내리칩니다.');
def('mage',9,'typhoon','태풍 부르기','Typhoon','storm','field',70,35,{mult:1.3,rad:260,dur:7,pull:1,stun:.15},'태풍을 불러 앉혀 넓은 땅의 적을 휘감아 찢습니다.');
def('mage',9,'rendingsky','하늘 가르기','Rending Sky','storm','beam',60,10,{mult:8,len:720,w:46,stun:1},'구름층을 가르며 벼락과 바람을 한 줄로 내리칩니다.');
// 대지
def('mage',1,'stoneset','돌 굳히기','Stoneset','earth','shield',8,12,{mult:1.6,flat:12,dur:10},'살갗을 돌처럼 굳혀 피해를 막습니다.');
def('mage',1,'crackstone','돌 쪼개기','Crack Stone','earth','bolt',4,.5,{mult:1.2,spd:520,r:6},'돌을 쪼개 그 조각을 날립니다.');
def('mage',2,'earthshaping','흙 다루기','Earth Shaping','earth','nova',8,3,{mult:1,rad:110,knock:60},'발밑 흙을 솟구쳐 둘레를 밀어냅니다.');
def('mage',2,'sandshaping','모래 다루기','Sand Shaping','earth','cone',7,1.5,{mult:1,range:170,ang:1,slow:1},'모래를 부채꼴로 흩뿌려 눈을 가리고 느리게 합니다.');
def('mage',3,'stonethrow','돌 던지기','Stone Throw','earth','bolt',9,1.1,{mult:2,spd:460,r:11,aoe:60,stun:.6},'돌덩이를 뜯어내 날려 맞은 자리를 부숩니다.');
def('mage',3,'mudgrasp','진흙 손','Mud Grasp','earth','bolt',10,4,{mult:.8,spd:480,r:8,freeze:2.2},'진흙 손으로 적의 발목을 붙잡아 묶습니다.');
def('mage',4,'quicksand','모래 늪','Quicksand','earth','field',16,9,{mult:.4,rad:130,dur:6,slow:1,pull:1},'단단한 땅을 모래 늪으로 바꿔 적을 빨아들입니다.');
def('mage',5,'obsidian','흑요석 가시','Obsidian Spikes','earth','bolt',18,1.5,{mult:1.3,spd:700,r:6,cnt:5,spread:.16,pierce:1,stun:.3},'녹인 돌을 날아가는 순간 굳혀 검은 가시로 쏩니다.');
def('mage',6,'stoneguardian','돌 수호자','Stone Guardian','earth','summon',34,45,{mult:2,dur:25,hp:3,form:'golem'},'흙과 돌로 움직이는 몸을 빚어 함께 싸웁니다.');
def('mage',6,'crystallance','수정 창','Crystal Lance','earth','beam',24,3,{mult:3.4,len:420,w:22,stun:.5},'빛을 가둔 수정을 창처럼 솟게 해 일직선을 꿰뚫습니다.');
def('mage',7,'earthquake','지진','Earthquake','earth','field',44,14,{mult:1.1,rad:230,dur:4,stun:.4},'넓은 땅을 뒤흔들어 위의 적을 계속 쓰러뜨립니다.');
def('mage',7,'jaws','땅의 이빨','Jaws of the Earth','earth','strike',34,6,{mult:6,rad:95,delay:.3,stun:1.5},'땅을 갈라 이빨처럼 닫아 한 자리를 깨물어 부숩니다.');
def('mage',8,'magmariver','용암 강','River of Magma','earth','beam',44,7,{mult:4.5,len:520,w:44,burn:1},'용암을 강처럼 흘려보냅니다. 화염 학파와의 융합.');
def('mage',9,'raisemountain','산 일으키기','Raise the Mountain','earth','nova',70,20,{mult:7,rad:300,knock:160,stun:2},'평지에서 산을 밀어 올려 둘레의 모든 것을 날려 버립니다.');
def('mage',9,'splitcanyon','협곡 가르기','Split the Canyon','earth','beam',66,14,{mult:9,len:720,w:70,stun:1.2},'산맥을 가르듯 땅을 한 줄로 쪼갭니다.');
// 이치 (봉인과 결계 · 공간 · 빛 · 변성)
def('mage',1,'light','빛','Light','light','bolt',3,.35,{mult:1,spd:700,r:5},'빛 한 줄기를 쏩니다. 부정한 것(언데드)에게 두 배.');
def('mage',2,'hold','붙들기','Hold','arcane','nova',10,6,{mult:.4,rad:120,stun:1.4},'둘레의 움직이는 것을 한꺼번에 붙듭니다.');
def('mage',4,'heatoflight','빛의 열','Heat of Light','light','beam',14,1.6,{mult:2.2,len:400,w:16,burn:1},'빛을 모아 열로 바꿔 한 줄기로 쏩니다.');
def('mage',5,'slowtime','시간 늦추기','Slow Time','arcane','nova',26,14,{mult:0,rad:300,slow:1,stun:.3},'둘레의 시간을 늦춰 모든 적을 느리게 합니다.');
def('mage',5,'lancelight','빛의 창','Spear of Light','light','bolt',18,1.4,{mult:2.6,spd:850,r:8,pierce:1},'빛을 창으로 벼려 줄지어 선 적을 꿰뚫습니다.');
def('mage',6,'spacetwist','공간 비틀기','Twist Space','arcane','strike',30,7,{mult:4.2,rad:120,delay:.45,stun:1},'한 점의 공간을 비틀어 접었다 펼쳐 안의 적을 짓이깁니다.');
def('mage',6,'lightrain','빛의 비','Rain of Light','light','rain',32,10,{mult:1.1,rad:150,dur:3,rate:8,srad:34},'빛의 화살을 비처럼 내립니다.');
def('mage',7,'spaceprison','공간 감옥','Space Prison','arcane','bolt',30,8,{mult:1.5,spd:560,r:10,freeze:4.5,aoe:110},'공간을 접어 맞은 자리의 적들을 가둡니다.');
def('mage',7,'dawnblade','새벽의 칼','Blade of Dawn','light','cone',30,4,{mult:4,range:230,ang:1.4},'새벽빛을 칼로 쥐고 앞쪽을 크게 벱니다.');
def('mage',8,'rewind','되감기','Rewind','arcane','heal',50,120,{pct:.45,mult:1,resetcd:1},'몸의 시간을 몇 호흡 되감아 상처를 되돌리고, 다른 마법의 재사용 대기를 모두 지웁니다.');
def('mage',9,'spacerend','공간 가르기','Rend Space','arcane','beam',64,12,{mult:9,len:680,w:56,stun:1.5},'공간 자체를 한 줄로 갈라 그 위의 모든 것을 찢습니다.');
def('mage',9,'starlight','별빛 부르기','Call Starlight','light','rain',66,18,{mult:2.4,rad:240,dur:5,rate:10,srad:48,stun:.3},'밤하늘의 별빛을 끌어내려 넓은 땅에 쏟습니다.');
