// ---- 비전 마법 (마법사) ----
def('mage',1,'spark','불티','Spark','fire','bolt',3,.3,{mult:1,spd:640,r:5},'손끝에서 불티를 튀겨 쏩니다. 모든 불 마법의 시작.');
def('mage',1,'stop','멈춤','Stop','arcane','bolt',6,3,{mult:.5,spd:720,r:6,stun:1.6},'움직이는 것을 잠시 멈춥니다. 맞은 적은 1.6초 동안 움직이지 못합니다.');
def('mage',1,'gust','돌풍','Gust','wind','cone',5,2,{mult:.7,range:150,ang:1.2,knock:90},'한 줄기 바람으로 앞쪽의 적을 밀어냅니다.');
def('mage',2,'static','정전기','Static Spark','storm','chain',5,.9,{mult:.9,jumps:3},'손끝의 번쩍임이 가까운 적 셋에게 튑니다. 벼락 마법의 첫걸음.');
def('mage',2,'waterjet','물줄기','Water Jet','ice','bolt',5,.7,{mult:1.1,spd:560,r:7,slow:1,knock:40},'물을 가늘고 세게 뿜어 밀어내고 느리게 합니다.');
def('mage',2,'ease','피로 덜기','Ease Fatigue','life','passive',0,0,{pv:{spd:[.08,.012]}},'몸의 무게를 늘 덜어 둡니다. 패시브: 이동 속도가 오릅니다.');
def('mage',3,'firebolt','화염 화살','Fire Bolt','fire','bolt',6,.5,{mult:1.5,spd:500,r:8,burn:1},'불덩이를 날려 보냅니다. 맞은 적은 3초간 불탑니다. 전투 마법사의 기본기.');
def('mage',3,'frost','서리','Frost','ice','bolt',7,.8,{mult:1.2,spd:480,r:7,freeze:1},'물이 스스로 멈추고 싶게 만들어 맞은 적을 1초 동안 얼립니다.');
def('mage',3,'windblade','바람 칼날','Wind Blade','wind','bolt',6,.6,{mult:1.3,spd:720,r:7,pierce:1},'날처럼 벼린 바람이 줄지어 선 적을 모두 꿰뚫습니다.');
def('mage',3,'blink','짧은 도약','Short Leap','arcane','blink',10,5,{range:260},'눈에 보이는 곳까지 한순간에 옮겨 갑니다.');
def('mage',3,'flash','섬광','Flash','light','nova',10,6,{mult:.6,rad:130,stun:1.2},'빛을 모아 한순간에 터뜨려 주변의 적을 멈칫하게 합니다. 언데드에게 두 배.');
def('mage',4,'frostarrow','서리 화살','Frost Arrows','ice','bolt',9,.9,{mult:1,spd:540,r:6,cnt:3,spread:.2,slow:1},'얼음 조각 세 개를 부채꼴로 쏩니다.');
def('mage',4,'firewall','화염 방벽','Wall of Fire','fire','field',16,7,{mult:.5,rad:80,dur:5,burn:1},'땅에 뿌리내린 불길을 세워 5초 동안 태웁니다.');
def('mage',4,'fissure','땅 가르기','Fissure','earth','beam',14,4,{mult:1.6,len:320,w:22,stun:.8},'앞쪽 땅에 균열을 내어 발밑을 무너뜨립니다.');
def('mage',4,'shieldcircle','방패의 원','Circle of Shields','arcane','shield',16,14,{mult:3,flat:20,dur:10},'작은 원 안으로 날아드는 것을 멈춰 10초 동안 피해를 흡수합니다.');
def('mage',5,'fireburst','화염 폭발','Fireburst','fire','bolt',14,1.1,{mult:2,spd:430,r:10,aoe:90,burn:1},'날아간 불덩이가 터지며 사방으로 퍼집니다.');
def('mage',5,'lightning','번개','Lightning','storm','beam',12,1.2,{mult:2.1,len:420,w:14,stun:.3},'손끝에서 벼락을 뽑아 일직선의 적을 모두 꿰뚫습니다.');
def('mage',5,'iceprison','얼음 감옥','Ice Prison','ice','bolt',16,6,{mult:1,spd:520,r:8,freeze:3.5},'맞은 적을 3.5초 동안 통째로 얼음 속에 가둡니다.');
def('mage',5,'stonerain','돌비','Stone Rain','earth','rain',24,9,{mult:.9,rad:120,dur:2.5,rate:5,srad:40,stun:.4},'하늘로 던져 올린 돌들을 비처럼 떨어뜨립니다.');
def('mage',5,'arcaneheal','비전 치유','Arcane Healing','life','heal',20,8,{pct:.18,mult:1.2},'몸속 마나의 흐름을 되돌려 상처를 막습니다. 사제의 치유보다 약합니다.');
def('mage',6,'blizzard','눈보라','Blizzard','ice','field',30,10,{mult:.45,rad:140,dur:4,slow:1},'얼음 섞인 바람을 4초 동안 몰아쳐 적을 느리게 합니다.');
def('mage',6,'quake','땅울림','Quake','earth','nova',24,8,{mult:1.4,rad:170,stun:1.5},'땅을 한 번 크게 울려 둘레의 적을 모두 쓰러뜨립니다.');
def('mage',6,'twinflames','겹친 불화살','Twin Flames','fire','bolt',12,.8,{mult:1.6,spd:520,r:8,cnt:2,spread:.14,burn:1},'들숨과 날숨에 불화살 둘을 겹쳐 쏩니다.');
def('mage',6,'lightspear','번개 창','Lightning Spear','storm','beam',20,2.5,{mult:3.2,len:520,w:12,stun:.5},'벼락을 창처럼 벼려 멀리까지 꿰뚫습니다.');
def('mage',6,'firebird','불새','Firebird','fire','bolt',22,4,{mult:1.4,spd:330,r:9,cnt:3,spread:.7,homing:1,burn:1},'불의 정령을 새의 모습으로 불러 적을 쫓게 합니다.');
def('mage',7,'chainlightning','번개 사슬','Chain Lightning','storm','chain',22,1.4,{mult:2.2,jumps:6},'벼락이 적에서 적으로 여섯 번 튀며 퍼집니다.');
def('mage',7,'thunderrain','벼락 비','Thunder Rain','storm','rain',36,11,{mult:1.4,rad:150,dur:3,rate:6,srad:38,stun:.3},'하늘에서 여러 줄기 벼락을 동시에 떨어뜨립니다.');
def('mage',7,'pillar','불기둥','Pillar of Flame','fire','strike',30,6,{mult:4,rad:100,delay:.35,burn:1},'하늘로 솟는 불기둥으로 적의 무리를 태웁니다.');
def('mage',7,'sunflame','햇불','Sunflame','light','beam',26,3,{mult:3.4,len:560,w:16,burn:1},'빛에 불을 실어 한 줄기 광선으로 쏩니다. 빛과 화염의 융합.');
def('mage',7,'frozenground','빙결의 대지','Frozen Earth','ice','nova',34,12,{mult:1.6,rad:240,freeze:2.5},'넓은 땅을 한꺼번에 얼려 주변의 적을 2.5초 동안 가둡니다.');
def('mage',8,'dragonbreath','용의 숨결','Dragon\'s Breath','fire','cone',34,5,{mult:3.6,range:270,ang:1,burn:1},'부채꼴로 쏟아지는 불길. 성문도 녹입니다.');
def('mage',8,'timestop','시간 정지','Time Stop','arcane','nova',40,60,{mult:0,rad:340,freeze:4},'좁은 공간의 시간을 몇 호흡 동안 완전히 멈춥니다. 주변의 적이 4초 동안 멈춥니다.');
def('mage',8,'callstorm','폭풍 부르기','Call the Storm','storm','storm',50,40,{mult:2.4,dur:8,rate:4,range:420},'8초 동안 내 둘레에 폭풍을 불러 앉혀 적에게 벼락을 내립니다.');
def('mage',8,'stonebody','돌의 몸','Body of Stone','earth','invuln',30,75,{dur:3},'몸을 잠시 돌로 바꿔 3초 동안 어떤 피해도 받지 않습니다.');
def('mage',8,'firebirdflock','불새 무리','Flock of Firebirds','fire','bolt',45,10,{mult:1.8,spd:320,r:9,cnt:8,spread:.8,homing:1,burn:1},'수십 마리의 불새를 한꺼번에 불러 하늘을 덮습니다.');
def('mage',9,'skyfire','하늘불','Skyfire','fire','rain',60,18,{mult:2,rad:210,dur:4,rate:10,srad:50,burn:1},'하늘에서 불비를 쏟는 전장 마법. 발케르가 두려움을 사는 이유.');
def('mage',9,'heavenbolt','천공의 뇌정','Heaven\'s Thunderbolt','storm','strike',55,12,{mult:9,rad:120,delay:.25,stun:2},'구름 위의 벼락을 한곳에 모아 내리꽂습니다.');
def('mage',9,'sunfall','해 떨어뜨리기','Sunfall','light','strike',70,20,{mult:10,rad:170,delay:1,fall:1,burn:1},'하늘에서 작은 해를 떨어뜨리듯 빛과 불을 한 점에 쏟습니다.');
def('mage',9,'glacier','빙하 부르기','Call the Glacier','ice','cone',55,14,{mult:4,range:330,ang:1.3,freeze:3},'산 위의 얼음을 끌어내려 앞쪽을 통째로 얼립니다.');
// ---- 신성 마법 (사제) ----
def('priest',1,'holyspark','성스러운 불티','Holy Spark','holy','bolt',3,.3,{mult:1,spd:620,r:5},'작은 빛의 불티를 쏩니다. 부정한 것(언데드)에게 두 배.');
def('priest',1,'minorheal','작은 치유','Minor Healing','holy','heal',10,3,{pct:.12,mult:1.2,role:'quick'},'곧바로 작은 상처를 아물게 합니다. 재사용이 짧아 자주 쓰는 기본 치유.');
def('priest',1,'lightward','빛의 막','Veil of Light','holy','shield',10,8,{mult:1.6,flat:10,dur:8,role:'quick'},'얇은 빛의 막을 둘러 8초 동안 작은 피해를 흡수합니다. 재사용이 짧은 기본 보호막.');
def('priest',1,'blessing','축복','Blessing','holy','buff',10,25,{dur:20,dmg:.05,regen:1},'용기와 작은 행운. 오래 가는 축복: 피해 5% 증가, 마나 회복 증가.');
def('priest',2,'lightarrow','빛의 화살','Arrow of Light','holy','bolt',5,.5,{mult:1.4,spd:680,r:7},'새벽빛을 화살처럼 쏩니다.');
def('priest',2,'faith','믿음의 힘','Strength of Faith','holy','passive',0,0,{pv:{dmg:[.03,.004]}},'흔들리지 않는 믿음이 팔에 힘을 싣습니다. 패시브: 피해가 늘 조금 오릅니다(스킬 레벨마다 천천히).');
def('priest',2,'symbolflash','성표 섬광','Holy Symbol Flash','holy','cone',9,3,{mult:1.1,range:180,ang:1.1,stun:.6},'성표를 들어 앞쪽으로 빛을 쏟아 적을 멈칫하게 합니다.');
def('priest',3,'javelin','빛의 투창','Javelin of Light','holy','bolt',9,1,{mult:1.8,spd:640,r:8,pierce:1},'빛을 투창으로 벼려 던져 줄지어 선 적을 꿰뚫습니다.');
def('priest',3,'closewounds','상처 봉합','Close Wounds','holy','heal',20,12,{pct:.2,mult:1.6,low:1.5,role:'triage'},'깊은 상처를 붙입니다. 생명력이 적을수록 더 많이 낫습니다(빈사일 때 최대 2.5배).');
def('priest',3,'divineshield','신성 방패','Divine Shield','holy','shield',24,45,{mult:4.5,flat:30,dur:8,role:'big'},'위급할 때 큰 빛의 방패로 8초 동안 많은 피해를 흡수합니다. 재사용 대기가 깁니다.');
def('priest',3,'turnundead','부정 퇴치','Turn Undead','holy','nova',16,8,{mult:1,rad:180,ud:4,knock:80},'주변의 언데드와 생명술 피조물을 물리칩니다. 언데드에게 네 배.');
def('priest',4,'holyburst','성스러운 폭발','Holy Burst','holy','nova',16,4,{mult:1.6,rad:150},'사방으로 빛을 터뜨립니다.');
def('priest',4,'chainoflight','빛의 사슬 번개','Chain of Light','holy','chain',18,1.6,{mult:1.8,jumps:5},'빛이 적에서 적으로 다섯 번 옮겨 갑니다.');
def('priest',4,'holychains','성스러운 사슬','Holy Chains','holy','bolt',14,6,{mult:.9,spd:560,r:7,stun:2.5},'부정한 것을 은총의 사슬로 2.5초 동안 묶습니다.');
def('priest',4,'grace','신의 가호','Divine Grace','holy','ward',24,60,{dur:20,heal:.25,role:'cheat'},'20초 안에 치명적인 일격을 한 번 비껴가게 합니다(생명력 25%로).');
def('priest',5,'pillaroflight','빛의 기둥','Pillar of Light','holy','strike',22,4,{mult:3.5,rad:90,delay:.3},'한 곳에 빛의 기둥을 떨어뜨립니다.');
def('priest',5,'lingering','머무는 치유','Lingering Heal','holy','hot',26,30,{dur:20,pct:.35,mult:2,mana:.25,role:'hot-mana'},'20초 동안 은총이 머물러 생명력과 함께 마나(최대치의 25%)도 천천히 차오릅니다. 나에게만.');
def('priest',5,'waveoflight','빛의 물결','Wave of Light','holy','cone',22,4,{mult:2.4,range:300,ang:.9,knock:60},'앞으로 밀려가는 빛의 물결.');
def('priest',5,'exorcircle','퇴마의 원','Circle of Exorcism','holy','field',26,12,{mult:.6,rad:150,dur:5,self:1,ud:3},'내 둘레에 원을 그어 5초 동안 부정한 것을 몰아냅니다. 언데드에게 세 배.');
def('priest',5,'herobless','영웅의 축복','Hero\'s Blessing','holy','buff',26,60,{burst:1,dur:12,dmg:.25,spd:.15},'12초 동안 힘과 날렵함을 한꺼번에 북돋습니다(피해 25%, 이동 속도 15%). 짧은 강화입니다.');
def('priest',6,'rainoflight','빛의 비','Rain of Light','holy','rain',32,10,{mult:1.2,rad:150,dur:3,rate:8,srad:34},'하늘에서 빛의 화살을 비처럼 내립니다.');
def('priest',6,'greaterheal','대치유','Greater Healing','holy','heal',36,12,{pct:.45,mult:2.6,role:'big-cast'},'잠시 기도를 올린 뒤(시전 시간) 생명력을 크게 회복합니다.');
def('priest',6,'healcircle','치유의 원','Circle of Healing','holy','field',30,30,{mult:0,rad:110,dur:8,self:1,heal:.06,role:'aura'},'8초 동안 나를 따라다니는 치유의 원. 움직이면서도 천천히 낫습니다.');
def('priest',6,'burningsigil','타오르는 성표','Burning Sigil','holy','field',28,9,{mult:.8,rad:100,dur:6,burn:1},'땅에 성표를 그어 밟는 적을 6초 동안 태웁니다.');
def('priest',7,'judgment','심판의 빛','Light of Judgment','holy','strike',40,9,{mult:5,rad:170,delay:.6},'하늘에서 빛의 기둥을 내려 넓은 범위를 정화합니다.');
def('priest',7,'thunderprayer','천둥 같은 기도','Thunderous Prayer','holy','storm',44,30,{mult:2.4,dur:7,rate:4,range:400},'7초 동안 하늘의 빛이 벼락처럼 주변의 적에게 내리꽂힙니다.');
def('priest',7,'oath','불굴의 서약','Unyielding Oath','holy','buff',34,90,{burst:1,dur:6,dr:.15,floor:1,role:'last-stand'},'6초 동안 어떤 일격에도 생명력 1 아래로 쓰러지지 않고, 받는 피해가 15% 줄어듭니다. 그 사이에 치유하세요.');
def('priest',7,'holysun','성스러운 해','Holy Sun','holy','field',46,18,{mult:1,rad:180,dur:6,burn:1},'작은 해를 띄워 6초 동안 그 아래의 적을 태웁니다.');
def('priest',8,'godspear','신의 창','Spear of God','holy','strike',44,8,{mult:11,rad:70,delay:.4,stun:1.5},'하늘에서 거대한 빛의 창을 내립니다.');
def('priest',8,'greatjudgment','대심판','Great Judgment','holy','nova',56,14,{mult:3.5,rad:300},'둘레의 모든 적을 한꺼번에 심판합니다.');
def('priest',8,'inviolable','불가침','Inviolable','holy','invuln',40,120,{dur:4,role:'invuln'},'4초 동안 어떤 해도 닿지 못합니다. 재사용 대기가 아주 깁니다.');
def('priest',8,'regeneration','재생','Regeneration','holy','heal',50,120,{pct:1,mult:0,role:'full'},'생명력을 모두 되살립니다. 재사용 대기가 길어 정말 위급할 때만.');
def('priest',9,'wrath','하늘의 노여움','Wrath of Heaven','holy','rain',70,25,{mult:2.4,rad:230,dur:5,rate:10,srad:46},'전설 속 심판. 한 군대가 하룻밤에 흩어졌다고 전해집니다.');
def('priest',9,'thousandspears','천 개의 빛창','Thousand Spears of Light','holy','bolt',64,12,{mult:2,spd:420,r:8,cnt:12,spread:.5236,homing:1},'사방으로 빛의 창을 내려 적을 쫓게 합니다.');
def('priest',9,'returnmiracle','귀환의 기적','Miracle of Return','holy','ward',45,240,{dur:90,heal:1,inv:3,role:'revive'},'90초 안에 쓰러지면 생명력을 모두 되찾고 일어서며, 3초 동안 어떤 해도 닿지 못합니다.');
def('priest',9,'sunsword','태양의 검','Sword of the Sun','holy','cone',60,8,{mult:6,range:300,ang:1.6,burn:1},'해를 칼로 쥐고 앞쪽을 크게 벱니다.');

